S15_User_Auth_and_Sessions/library/catalog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('create_book/', views.BookCreate.as_view(), name='create_book'),
    path('book/<int:pk>/', views.BookDetail.as_view(), name='book_detail'),
    path("my_view", views.my_view, name="my_view"),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path("profile/", views.CheckedOutBooksByUserView.as_view(), name="profile"),
]

S15_User_Auth_and_Sessions/library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

urlpatterns = [
    path('catalog/', include("catalog.urls")),
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(url="catalog/")),
    path("accounts/", include("django.contrib.auth.urls"))
]

S15_User_Auth_and_Sessions/library/catalog/models.py
import uuid
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User

# Create your models here.
class Genre(models.Model):
    name = models.CharField(max_length=150)

    def __str__(self):
        return self.name
    
class Language(models.Model):
    name = models.CharField(max_length=200)
    def __str__(self):
        return self.name
    
class Book(models.Model):
    title = models.CharField(max_length=200)
    author = models.ForeignKey("Author", on_delete=models.SET_NULL, null=True)
    summary = models.TextField(max_length=600)
    isbn = models.CharField("ISBN", max_length=13, unique=True)
    genre = models.ManyToManyField(Genre)
    language = models.ForeignKey("Language", on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", kwargs={"pk": self.pk})

class Author(models.Model):
    first_name = models.CharField(max_length=200)
    last_name = models.CharField(max_length=200)
    date_of_birth = models.DateField(null=True, blank=True)

    class Meta:
        ordering = ["last_name", "first_name"]
    
    def get_absolute_url(self):
        return reverse("author_detail", kwargs={"pk": self.pk})
    
    def __str__(self):
        return f"{self.first_name} {self.last_name}"
    
class BookInstance(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4)
    book = models.ForeignKey("Book", on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    LOAN_STATUS = (
        ("m", "Maintenance"),
        ("o", "On Loan"),
        ("a", "Available"),
        ("r", "Reserved"),
    )

    status = models.CharField(max_length=1, choices=LOAN_STATUS, blank=True, default="m")

    class Meta:
        ordering = ["due_back"]

    def __str__(self):
        return f"{self.id} ({self.book.title})"

S15_User_Auth_and_Sessions/library/catalog/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.shortcuts import render
from django.http import HttpResponse
from django.urls import reverse_lazy
from .models import Book, Author, BookInstance, Genre, Language
from django.views.generic import CreateView, DetailView, ListView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def index(request):
    num_books = Book.objects.all().count()
    num_instances = BookInstance.objects.all().count()

    num_instances_avail = BookInstance.objects.filter(status__exact="a").count()

    context = {
        "num_books": num_books,
        "num_instances": num_instances,
        "num_instances_avail": num_instances_avail,
    }

    return render(request, "catalog/index.html", context=context)

class BookCreate(LoginRequiredMixin, CreateView):
    model = Book
    fields = "__all__"

class BookDetail(DetailView):
    model = Book

@login_required
def my_view(request):
    return render(request, "catalog/my_view.html")

class SignUpView(CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = 'catalog/signup.html'

class CheckedOutBooksByUserView(LoginRequiredMixin, ListView):
    model = BookInstance
    template_name = "catalog/profile.html"
    paginate_by = 5

    def get_queryset(self):
        return BookInstance.objects.filter(borrower=self.request.user)

S15_User_Auth_and_Sessions/library/catalog/templates/catalog/book_detail.html
<h1>Detail for Book</h1>
{{book}}

S15_User_Auth_and_Sessions/library/catalog/templates/catalog/book_form.html
<h1>Create new Book</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Create Book">
</form>

S15_User_Auth_and_Sessions/library/catalog/templates/catalog/index.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>HOMEPAGE</h1>
    <p>Total Books: {{num_books}}</p>
    <p>Num Available: {{num_instances_avail}}</p>
    {% if user.is_authenticated %}
        <p>You are logged in</p>
        <p>Welcome: {{user.get_username}}</p>
        <a href="{% url "logout" %}?next={{request.path}}">Logout Here</a>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url "login" %}?next={{request.path}}">Login Here</a>
    {% endif %}
</body>
</html>

S15_User_Auth_and_Sessions/library/catalog/templates/catalog/my_view.html
<h1>LOGGED IN USERS ONLY</h1>

S15_User_Auth_and_Sessions/library/catalog/templates/catalog/profile.html
<h1>Welcome to your profile!</h1>
<h2>Here are your books checked out:</h2>

{% for book in bookinstance_list %}
    <p>{{book}}</p>
{% endfor %}

S15_User_Auth_and_Sessions/library/catalog/templates/catalog/signup.html
<h1>Register New User Here</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="signup">
</form>