S12_Admin/my_car_sit/cars/urls.py
from django.urls import path
from . import views

app_name = 'cars'

urlpatterns = [
    path('list/', views.list, name='list'),
    path('add/', views.add, name='add'),
    path('delete/', views.delete, name='delete'),
]

S12_Admin/my_car_sit/my_car_sit/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cars/', include('cars.urls'))
]

S12_Admin/my_car_sit/cars/models.py
from django.db import models

# Create your models here.
class Car(models.Model):
    # pk
    brand = models.CharField(max_length=30)
    year = models.IntegerField()

    def __str__(self):
        return f"Car is {self.brand} {self.year}"

S12_Admin/my_car_sit/cars/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from . import models

# Create your views here.
def list(request):
    all_cars = models.Car.objects.all()
    context = {'all_cars': all_cars}
    return render(request, 'cars/list.html', context=context)

def add(request):
    if request.POST:
        brand = request.POST["brand"]
        year  = int(request.POST["year"])
        models.Car.objects.create(brand=brand, year=year)
        # if user submitted new car --> List.html
        return redirect(reverse("cars:list"))
    else:
        return render(request, 'cars/add.html')

def delete(request):
    if request.POST:
        pk = request.POST['pk']
        try:
            models.Car.objects.get(pk=pk).delete()
            return redirect(reverse("cars:list"))
        except:
            print("Primary Key NOT found!")
            return redirect(reverse("cars:list"))
    else:
        return render(request, 'cars/delete.html')

S12_Admin/my_car_sit/cars/templates/cars/add.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>ADD.HTML</h1>
    <h2>Add a new car to DB:</h2>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="brand">Brand:</label>
            <input type="text" class="form-control" id="brand" name="brand">
        </div>
        <divclass="form-group">
            <label for="year">Year:</label>
            <input type="text" class="form-control" id="year" name="year">
        </div>
        <input class="btn btn-primary" type="submit">
    </form>
</div>
{% endblock%}

S12_Admin/my_car_sit/cars/templates/cars/delete.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1>DELETE.HTML</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="pk">PK Number:</label>
            <input type="text" class="form-control" id="pk" name="pk">
        </div>
        <input class="btn btn-primary" type="submit">
    </form>
</div>
{% endblock%}

S12_Admin/my_car_sit/cars/templates/cars/list.html
{% extends "base.html" %}

{% block content %}
<div class = 'container'>
    <h1>LIST.HTML</h1>
    <ul>
        {% for car in all_cars %}
            <li>{{car}}</li>
        {% endfor %}
    </ul>
</div>
{% endblock%}

S12_Admin/my_car_sit/templates/base.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<body>
    <!-- NAVBAR -->
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link" href="{% url 'cars:list' %}">LIST</a>
              <a class="nav-link" href="{% url 'cars:add' %}">ADD</a>
              <a class="nav-link" href="{% url 'cars:delete' %}">DELETE</a>
            </div>
          </div>
        </div>
      </nav>
    {% block content %}

    {% endblock %}
</body>
</html>