S14_Class_Based_Views/school/classroom/urls.py
from django.urls import path
from .views import HomeView, ThankYouView, ContactFormView, TeacherCreatView, TeacherListView, TeacherDetailView, TeacherUpdateView, TeacherDeleteView

app_name = "classroom"

urlpatterns = [
    #path("", home_view, name="home")
    path("", HomeView.as_view(), name="home"),
    path("thank_you/", ThankYouView.as_view(), name="thank_you"),
    path("contact/", ContactFormView.as_view(), name="contact"),
    path("create_teacher/", TeacherCreatView.as_view(), name="create_teacher"),
    path("list_teacher/", TeacherListView.as_view(), name="list_teacher"),
    path("teacher_detail/<int:pk>", TeacherDetailView.as_view(), name="detail_teacher"),
    path("update_teacher/<int:pk>", TeacherUpdateView.as_view(), name="update_teacher"),
    path("delete_teacher/<int:pk>", TeacherDeleteView.as_view(), name="delete_teacher"),
]

S14_Class_Based_Views/school/school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("classroom/", include("classroom.urls"))
]

S14_Class_Based_Views/school/classroom/models.py
from django.db import models

# Create your models here.
class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

S14_Class_Based_Views/school/classroom/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField()
    messgae = forms.CharField(widget=forms.Textarea)

S14_Class_Based_Views/school/classroom/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse, reverse_lazy
from classroom.models import Teacher
from classroom.forms import ContactForm

# Create your views here.
# def home_view(request):
#     return render(request, "classroom/home.html")

class HomeView(TemplateView):
    template_name = "classroom/home.html"

class ThankYouView(TemplateView):
    template_name = "classroom/thank_you.html"

class TeacherCreatView(CreateView):
    model =  Teacher
    fields = "__all__"
    #success_url = reverse_lazy("classroom:thank_you")
    success_url = reverse_lazy("classroom:list_teacher")
    
class TeacherListView(ListView):
    model =  Teacher
    queryset = Teacher.objects.order_by("first_name")
    context_object_name = "teacher_list"
    #fields = "__all__"
    #success_url = reverse_lazy("classroom:thank_you")

class TeacherDetailView(DetailView):
    model = Teacher

class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = ["last_name", "subject"]
    success_url = reverse_lazy("classroom:list_teacher")

class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy("classroom:list_teacher")

class ContactFormView(FormView):
    form_class = ContactForm
    template_name = "classroom/contact.html"

    # URL? URL NOT A TEMPLATE FILE
    #success_url = "/classroom/thank_you/"
    success_url = reverse_lazy("classroom:thank_you")

    # What to do with form
    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)
    

S14_Class_Based_Views/school/classroom/templates/classroom/contact.html
<h1>Form View Template (contact.html)</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

S14_Class_Based_Views/school/classroom/templates/classroom/home.html
<h1>Welcome to home.html</h1>
<ul>
    <li>
        <a href="{% url "classroom:thank_you" %}">THANK YOU PAGE</a>
    </li>
    <li>
        <a href="{% url "classroom:contact" %}">CONTACT FORM PAGE</a>
    </li>
    <li>
        <a href="{% url "classroom:create_teacher" %}">CREATE NEW TEACHER PAGE</a>
    </li>
    <li>
        <a href="{% url "classroom:list_teacher" %}">LIST TEACHER PAGE</a>
    </li>
</ul>

S14_Class_Based_Views/school/classroom/templates/classroom/teacher_confirm_delete.html
<h1>Are you sure you want to delete this teacher?</h1>
<h2>{{teacher}}</h2>

<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Confirm Delete">
</form>

S14_Class_Based_Views/school/classroom/templates/classroom/teacher_detail.html
<h1>Deatil View for Teacher</h1>
{{teacher}}

S14_Class_Based_Views/school/classroom/templates/classroom/teacher_form.html
<h1>TEACHER FORM</h1>
<form method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" value="Submit">
</form>

S14_Class_Based_Views/school/classroom/templates/classroom/teacher_list.html
<h1>List of Teachers (ListView)</h1>
<ul>
    {% for teacher in teacher_list %}
        <li>
            <a href="/classroom/teacher_detail/{{teacher.id}}">{{teacher.first_name}} {{teacher.last_name}}</a>
        </li>
        <ul>
            <li>
                <a href="/classroom/update_teacher/{{teacher.id}}">Update Information for {{teacher.last_name}}</a>
            </li>
            <li>
                <a href="/classroom/delete_teacher/{{teacher.id}}">Delete Information for {{teacher.last_name}}</a>
            </li>
        </ul>
        {% comment %} <li>{{teacher.first_name}} {{teacher.last_name}}</li> {% endcomment %}
    {% endfor %}
</ul>

S14_Class_Based_Views/school/classroom/templates/classroom/thank_you.html
<h1>Thank You!</h1>